DROP INDEX IF EXISTS idx_groups_created_by;
ALTER TABLE groups ALTER COLUMN description DROP DEFAULT;
ALTER TABLE groups ALTER COLUMN role DROP DEFAULT;
ALTER TABLE groups DROP COLUMN IF EXISTS created_by;
ALTER TABLE groups DROP COLUMN IF EXISTS name;
