package httpapi

import (
	"context"
	"crypto/subtle"
	"net/http"
	"strings"

	"diplom.com/m/internal/usecase"
)

type API struct {
	Auth      *usecase.AuthService
	Plans     *usecase.PlanService
	Goals     *usecase.GoalService
	Items     *usecase.PlanItemService
	Docs      *usecase.DocumentService
	Groups    *usecase.GroupService
	Analytics *usecase.AnalyticsService
	// InternalAnalytics backs the AI agent's read-only DB callbacks.
	InternalAnalytics *usecase.InternalAnalyticsService
	// InternalToken is the global shared secret for /api/* callbacks.
	// Per-session tokens (from Sessions) are accepted in addition to this
	// and carry an ownerID for per-tenant query scoping.
	InternalToken string
	// Sessions is the session store shared with AnalyticsService. The
	// internalAuth middleware validates per-session nonces from it.
	Sessions *usecase.SessionStore
}

func (a *API) Routes() http.Handler {
	mux := http.NewServeMux()

	mux.HandleFunc("GET /healthz", a.healthz)

	mux.HandleFunc("POST /v0/auth/token", a.token)
	mux.HandleFunc("POST /v0/auth/register", a.register)

	mux.Handle("GET /v0/plans", a.authenticated(a.listPlans))
	mux.Handle("POST /v0/plans", a.authenticated(a.createPlan))

	mux.Handle("GET /v0/plans/{id_plan}/goals", a.authenticated(a.listGoals))
	mux.Handle("POST /v0/plans/{id_plan}/goals", a.authenticated(a.createGoal))

	mux.Handle("GET /v0/plans/{id_plan}/goals/{id_goal}/items", a.authenticated(a.listItems))
	mux.Handle("POST /v0/plans/{id_plan}/goals/{id_goal}/items", a.authenticated(a.createItem))
	mux.Handle("PATCH /v0/plans/{id_plan}/goals/{id_goal}/items/{id_item}", a.authenticated(a.updateItem))

	// Both POST upload/{id_plan_item} and {id_document}/confirm share the
	// /v0/documents/{seg1}/{seg2} shape; the stdlib ServeMux can't disambiguate
	// them as separate wildcard patterns, so a single dispatcher handles both.
	mux.Handle("POST /v0/documents/{seg1}/{seg2}", a.authenticated(a.postDocumentAction))
	mux.Handle("GET /v0/documents", a.authenticated(a.listDocuments))
	mux.Handle("GET /v0/documents/{id_document}/download", a.authenticated(a.downloadDocument))
	mux.Handle("GET /v0/documents/{id_document}/storage", a.authenticated(a.getDocumentStorage))
	mux.Handle("GET /v0/documents/{id_document}", a.authenticated(a.getDocument))
	mux.Handle("PATCH /v0/documents/{id_document}", a.authenticated(a.patchDocument))

	// Corporate-account groups: shared workspaces where every member sees one
	// another's plans and documents.
	mux.Handle("GET /v0/groups", a.authenticated(a.listGroups))
	mux.Handle("POST /v0/groups", a.authenticated(a.createGroup))
	mux.Handle("GET /v0/groups/{id_group}", a.authenticated(a.getGroup))
	mux.Handle("POST /v0/groups/{id_group}/members", a.authenticated(a.addGroupMember))
	mux.Handle("DELETE /v0/groups/{id_group}/members/{id_member}", a.authenticated(a.removeGroupMember))

	mux.Handle("GET /v0/items/{id_item}/analytics", a.authenticated(a.getItemAnalytics))
	mux.Handle("POST /v0/items/{id_item}/analyze", a.authenticated(a.analyzeItem))

	// Internal callbacks for the AI analytics agent (shared-secret auth).
	mux.Handle("GET /api/schema", a.internalAuth(a.getSchema))
	mux.Handle("POST /api/analytics/query", a.internalAuth(a.runQuery))

	return mux
}

type ctxUserID struct{}

func (a *API) authenticated(next http.HandlerFunc) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		h := r.Header.Get("Authorization")
		if !strings.HasPrefix(h, "Bearer ") {
			writeError(w, http.StatusUnauthorized, "UNAUTHORIZED", "Missing bearer token")
			return
		}
		userID, err := a.Auth.ValidateAccessToken(strings.TrimPrefix(h, "Bearer "))
		if err != nil {
			writeError(w, http.StatusUnauthorized, "UNAUTHORIZED", "Invalid access token")
			return
		}
		next.ServeHTTP(w, r.WithContext(context.WithValue(r.Context(), ctxUserID{}, userID)))
	})
}

func userID(r *http.Request) int64 {
	v, _ := r.Context().Value(ctxUserID{}).(int64)
	return v
}

// ctxInternalOwnerID is the context key set by internalAuth when a per-session
// token is presented. Handlers use it to scope queries to the calling user.
type ctxInternalOwnerID struct{}

// internalAuth guards the AI-agent callbacks. It accepts two kinds of tokens:
//
//  1. Per-session nonce (preferred): generated by AnalyticsService when a user
//     calls /v0/items/{id}/analyze. Carries an ownerID; activates per-tenant
//     CTE scoping so the agent only sees that user's rows.
//
//  2. Global INTERNAL_API_TOKEN: backward-compat / manual testing. Grants
//     access but leaves ownerID=0 (unscoped — avoid in production).
func (a *API) internalAuth(next http.HandlerFunc) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		token := r.Header.Get("X-Internal-Token")

		// Per-session token path: scoped to the initiating user.
		if a.Sessions != nil {
			if ownerID, ok := a.Sessions.Lookup(token); ok {
				ctx := context.WithValue(r.Context(), ctxInternalOwnerID{}, ownerID)
				next.ServeHTTP(w, r.WithContext(ctx))
				return
			}
		}

		// Global token path: unscoped, for ops/manual testing.
		if a.InternalToken != "" && subtle.ConstantTimeCompare([]byte(token), []byte(a.InternalToken)) == 1 {
			next.ServeHTTP(w, r)
			return
		}

		writeError(w, http.StatusUnauthorized, "UNAUTHORIZED", "Invalid internal token")
	})
}

func (a *API) healthz(w http.ResponseWriter, r *http.Request) {
	writeJSON(w, http.StatusOK, map[string]string{"status": "ok"})
}

// WithCORS wraps a handler with permissive CORS headers so a browser frontend
// served from a different origin can call the API. Auth is a Bearer header
// (not a cookie), so a wildcard origin is acceptable. Preflight OPTIONS
// requests are answered with 204 and do not reach the wrapped handler.
func WithCORS(next http.Handler, origin string) http.Handler {
	if origin == "" {
		origin = "*"
	}
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		h := w.Header()
		h.Set("Access-Control-Allow-Origin", origin)
		h.Set("Access-Control-Allow-Methods", "GET, POST, PATCH, DELETE, OPTIONS")
		h.Set("Access-Control-Allow-Headers", "Authorization, Content-Type")
		h.Set("Access-Control-Max-Age", "86400")
		h.Add("Vary", "Origin")
		if r.Method == http.MethodOptions {
			w.WriteHeader(http.StatusNoContent)
			return
		}
		next.ServeHTTP(w, r)
	})
}
